/*
 * GCodeResult.h
 *
 *  Created on: 1 Oct 2017
 *      Author: David
 */

#ifndef SRC_GCODERESULT_H_
#define SRC_GCODERESULT_H_

#include <ecv_duet3d.h>
#include <cstdint>

// Enumeration to specify the result of attempting to process a GCode command
// CAUTION!
// 1. CAN messages only allow for a 4-bit result to be passed back, therefore if more result codes are added we must ensure that codes with
//    values > 15 are never generated by tool/ expansion boards.
// 2. Values of codes that are used by both the main board and by tool/expansion boards should not be changed, otherwise it may get very
//    confusing when main and expansion boards are running different sofware version numbers.
enum class GCodeResult : uint8_t
{
	notFinished,					// we haven't finished processing this command
	ok,								// we have finished processing this code in the current state, and if the GCodeState is 'normal' then we have finished it completely
	warning,						// the command succeeded but a warning was generated
	warningNotSupported,			// the command is not supported, but for this command we issue a warning not an error
	error,							// general error, the reason will be written to the associated reply buffer
	errorNotSupported,				// this command is not supported, and we treat it as an error because it's an important command
	notSupportedInCurrentMode,		// this command is supported in a different mode (FDM/Laser/CNC)
	stopped,						// we are halted because of an emergency stop
	badOrMissingParameter,			// a critical parameter is missing or has a bad value
	remoteInternalError,			// only used if CAN expansion is supported - can be sent by expansion boards, so don't change its number!

	// None of the following is generated by tool/expansion boards, so additional codes that are may be inserted here
	m291Cancelled,
	waitingForAckSoIgnored,			// we are waiting for a message box to be acknowledged so the command has been ignored
	noCanBuffer,					// only used if CAN expansion is supported - we failed to allocate a CAN buffer to send a message to an expansion board
	canResponseTimeout				// only used if CAN expansion is supported - timed out waiting for a response to a CAN message - the associated reply buffer may contain more info
};

constexpr const char *_ecv_array NoCanBufferMessage = "no CAN buffer available";

// Test whether the command succeeded
inline constexpr bool Succeeded(GCodeResult rslt) noexcept
{
	return rslt == GCodeResult::ok || rslt == GCodeResult::warning;
}

// Convert a true/false error/no-error indication to a GCodeResult
inline constexpr GCodeResult GetGCodeResultFromError(bool err) noexcept
{
	return (err) ? GCodeResult::error : GCodeResult::ok;
}

// Convert a true/false success/failure indication to a GCodeResult
inline constexpr GCodeResult GetGCodeResultFromSuccess(bool ok) noexcept
{
	return (ok) ? GCodeResult::ok : GCodeResult::error;
}

// Convert a true/false finished/not-finished indication to a GCodeResult
inline constexpr GCodeResult GetGCodeResultFromFinished(bool finished) noexcept
{
	return (finished) ? GCodeResult::ok : GCodeResult::notFinished;
}

#endif /* SRC_GCODERESULT_H_ */
